name: Backstage Platform Engg CI/CD pipeline for ${{ values.app_name }}
on:
  push:
    branches:
      - main
    paths:
      - src/**

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ '${{ secrets.DOCKERHUB_USERNAME }}' }}
          password: ${{ '${{ secrets.DOCKERHUB_TOKEN }}' }}

      - name: Reduce the GITHUB_SHA to 6 chars
        shell: bash
        run: |
          echo "COMMIT_ID=${GITHUB_SHA::6}" >> ${GITHUB_ENV}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: aumthakkar/${{ values.app_name }}:${{ '${{ env.COMMIT_ID }}' }}

    outputs: 
      commit_id: ${{ '${{ env.COMMIT_ID }}' }}

  cd:
    needs: ci
    runs-on: orbstack-runner
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v7

      - name: Using yq utility modify the tags from the Helm values file
        run: |          
          # Download and set up yq
          VERSION=v4.44.1
          PLATFORM=linux_arm64
          
          curl -L "https://github.com/mikefarah/yq/releases/download/${VERSION}/yq_${PLATFORM}" -o ./yq 
          chmod +x ./yq
          
          # Update the Helm values.yaml file with the latest commit_sha
          ./yq -i '.image.tag = "${{ '${{ needs.ci.outputs.commit_id }}' }}"' charts/${{ values.app_name }}/values-${{ values.app_env }}.yaml

      - name: Commit Changes to GitHub
        uses: EndBug/add-and-commit@v10
        with:
          message: "pushed the image with tag: ${{ '${{ needs.ci.outputs.commit_id }}' }}"

      - name: Install ArgoCD CLI
        run: |
          VERSION=$(curl -L -s https://raw.githubusercontent.com/argoproj/argo-cd/stable/VERSION)
          curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/download/v$VERSION/argocd-linux-amd64
          sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
          sudo chmod +x /usr/local/bin/argocd
          rm argocd-linux-amd64

      - name: ArgoCD login and App sync
        run: |
          argocd login argocd-server.argocd \
          --username ${{ '${{ secrets.ARGOCD_USERNAME }}' }} \
          --password ${{ '${{ secrets.ARGOCD_PASSWORD }}' }} \
          --insecure \
          --grpc-web

          # Create and sync the app
          REPO="https://github.com/aumthakkar/jun26-${{ values.app_name }}.git"
          
          # If not there add the Repo to ArgoCD
          argocd app list | grep -q ${REPO} || argocd repo add ${REPO}

          # Create app if not there already
          if argocd app get ${{ values.app_name }} > /dev/null 2>&1; then
            echo "Deleting old app - ${{ values.app_name }} for a new fresh install..."
            argocd app delete ${{ values.app_name }} -y --cascade --wait

            # Wait while the app gets deleted
            while argocd app get ${{ values.app_name }}; do
              echo "Waiting for App ${{ values.app_name }} to be deleted..."
              sleep 2
            done
            echo "App: ${{ values.app_name }} deleted."
          fi

          # Create the app
          argocd app create ${{ values.app_name }} \
          --dest-server https://kubernetes.default.svc \
          --dest-namespace dev \
          --path charts/${{ values.app_name }} \
          --repo ${REPO} \
          --revision main \
          --sync-option CreateNamespace=true \
          --sync-policy manual \
          --values values-${{ values.app_env }}.yaml

          argocd app sync ${{ values.app_name }}
          argocd app wait ${{ values.app_name }} --timeout 120





  